### ISSUE TITLE
Loudspeaker on/off while calling

### ISSUE THREAD

**Issue by ravirupareliya** [sinch/android-app-app-calling-headers#1]
Does there any way through which we can perform on/off operation for loudspeaker? Or we need to deal with AudioManager of android? 

I have tried with following method of AudioManager while calling but somehow it is not working.

```
audioManager.setSpeakerphoneOn(true);
```

Anything else is required to do this operation?

**Comment by spacedsweden** [comment]
Use the https://download.sinch.com/docs/android/latest/reference/index.html?com/sinch/android/rtc/SinchClient.html
