### ISSUE TITLE
establishTime is not timeInMills, its something different

### ISSUE THREAD

**Issue by ravirupareliya** [sinch/android-app-app-calling-headers#2]
Currently i am using calling api for app to app calling, and this is what i am getting when receiving call.

```
[startTime=1462874315, endTime=0, progressTime=0, establishTime=1462874321, terminationCause=NONE, packetsSent=0, packetsReceived=0, error=null]
```

here i thought startTime and establishTime is timeInMillis, but it's not. I need to implement timer, and if i am using System.currentTimeMillis() it gives approx 1 seconds delay in both device, so thought to use establishTime instead of System.currentTimeMillis().

**Comment by spacedsweden** [comment]
I would jusst start a local timer on callEstablished
